# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summarization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13summarization.proto\x12\x02pb\"!\n\x0eSummaryRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"#\n\x0fSummaryResponse\x12\x10\n\x08response\x18\x01 \x03(\t2F\n\rSummarization\x12\x35\n\nGetSummary\x12\x12.pb.SummaryRequest\x1a\x13.pb.SummaryResponseB\x06Z\x04./pbb\x06proto3')



_SUMMARYREQUEST = DESCRIPTOR.message_types_by_name['SummaryRequest']
_SUMMARYRESPONSE = DESCRIPTOR.message_types_by_name['SummaryResponse']
SummaryRequest = _reflection.GeneratedProtocolMessageType('SummaryRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYREQUEST,
  '__module__' : 'summarization_pb2'
  # @@protoc_insertion_point(class_scope:pb.SummaryRequest)
  })
_sym_db.RegisterMessage(SummaryRequest)

SummaryResponse = _reflection.GeneratedProtocolMessageType('SummaryResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYRESPONSE,
  '__module__' : 'summarization_pb2'
  # @@protoc_insertion_point(class_scope:pb.SummaryResponse)
  })
_sym_db.RegisterMessage(SummaryResponse)

_SUMMARIZATION = DESCRIPTOR.services_by_name['Summarization']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _SUMMARYREQUEST._serialized_start=27
  _SUMMARYREQUEST._serialized_end=60
  _SUMMARYRESPONSE._serialized_start=62
  _SUMMARYRESPONSE._serialized_end=97
  _SUMMARIZATION._serialized_start=99
  _SUMMARIZATION._serialized_end=169
# @@protoc_insertion_point(module_scope)
