# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import summarization_pb2 as summarization__pb2


class SummarizationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSummary = channel.unary_unary(
                '/pb.Summarization/GetSummary',
                request_serializer=summarization__pb2.SummaryRequest.SerializeToString,
                response_deserializer=summarization__pb2.SummaryResponse.FromString,
                )


class SummarizationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SummarizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSummary,
                    request_deserializer=summarization__pb2.SummaryRequest.FromString,
                    response_serializer=summarization__pb2.SummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Summarization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Summarization(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Summarization/GetSummary',
            summarization__pb2.SummaryRequest.SerializeToString,
            summarization__pb2.SummaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
